# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = joshxviii.animalese
archives_name = animalese-typing
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2

# Architectury
# https://www.curseforge.com/minecraft/mc-mods/architectury-api
architectury_version=20.1.16

# Fabric Dependencies
fabric_loader_version = 0.19.5
fabric_api_version = 0.155.3+26.1.2
# https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin
fabric_kotlin_version=1.14.1+kotlin.2.4.20

# Forge dependencies
neoforge_version = 26.1.2.94
# https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge/files
kotlin_for_forge_version=6.3.0