modLoader = "kotlinforforge"
loaderVersion = "[6.0,)"
#issueTrackerURL = ""
license = "MPL-2.0"

[[mods]]
modId = "animalese_mc"
version = "${version}"
displayName = "Animalese Typing"
authors = "joshxviii"
description = '''
Animalese Typing is a mod that plays animalese sounds as you type!
'''
#logoFile = ""

[[dependencies.animalese_mc]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animalese_mc]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "animalese-typing.mixins.json"
